sudo: false
language: c

cache:
  directories:
  - $HOME/.stack

env:
  - STACK_YAML=lts.yaml
  - STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - libgconf2-dev
    - libgmp-dev
    sources: hvr-ghc

before_install:
 - mkdir -p $HOME/.local/bin
 - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - stack setup

install:
 - stack install gtk2hs-buildtools
 - stack test -j2 --no-run-tests

script:
 - stack test
 - for c in example-configs/*-static;
   do
     cd "$c" &&
     stack build --stack-yaml=$STACK_YAML &&
     cd -;
   done
