sudo: false
language: c

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - ghc-8.0.1
    sources: hvr-ghc

before_install:
 - mkdir -p $HOME/.local/bin
 - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=/opt/ghc/8.0.1/bin:$PATH

install:
 - stack test -j2 --no-run-tests

script:
 - stack test
