name: yi-frontend-pango
version: '0.13'
synopsis: Pango frontend for Yi editor
maintainer: Dmitry Ivanov <ethercrow@gmail.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

dependencies:
    - base >= 4.8 && < 5
    - containers
    - filepath
    - gconf
    - glib  >= 0.13 && < 0.14
    - gtk >= 0.13 && < 0.15
    - microlens-platform
    - mtl
    - oo-prototypes
    - pango >= 0.13 && < 0.14
    - pointedlist
    - text
    - transformers-base
    - yi-core
    - yi-language
    - yi-rope

library:
    source-dirs: src
    exposed-modules:
        - Yi.Frontend.Pango
        - Yi.Frontend.Pango.Control