name: yi-language
version: '0.2.1'
synopsis: Collection of language-related Yi libraries.
maintainer: Dmitry Ivanov <ethercrow@gmail.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

#dependencies:
#  - base >=4.7 && <5
#  - array
#  - binary
#  - data-default
#  - template-haskell >= 2.4
#  - containers
#  - hashable >=1.1.2.5
#  - oo-prototypes
#  - pointedlist >= 0.5
#  - regex-base ==0.93.*
#  - regex-tdfa >= 1.1 && <1.3
#  - transformers-base
#  - unordered-containers >= 0.1.3 && < 0.3
#  - microlens-platform

library:
    source-dirs: src
    exposed-modules:
      - Yi.Buffer.Basic
      - Yi.Lexer.Alex
      - Yi.Lexer.Compilation
      - Yi.Regex
      - Yi.Region
      - Yi.Style
      - Yi.Style.Library
      - Yi.Syntax
      - Yi.Utils
    dependencies:
      - base >=4.7 && <5
      - array
      - binary
      - data-default
      - template-haskell >= 2.4
      - containers
      - hashable >=1.1.2.5
      - oo-prototypes
      - pointedlist >= 0.5
      - regex-base ==0.93.*
      - regex-tdfa >= 1.1 && <1.3
      - transformers-base
      - unordered-containers >= 0.1.3 && < 0.3
      - microlens-platform
    build-tools:
      - alex >= 3.0.3
    include-dirs:
      - src/Yi/Lexer

tests:
  tasty:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - yi-language