name: yi-language
version: 0.14.1
synopsis: Collection of language-related Yi libraries.
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

extra-source-files:
  - src/Yi/Lexer/common.hsinc

dependencies:
  - base >= 4.8 && < 5
  - array
  - binary
  - data-default
  - template-haskell >= 2.4
  - containers
  - hashable >=1.1.2.5
  - pointedlist >= 0.5
  - regex-base ==0.93.*
  - regex-tdfa >= 1.1 && <1.3
  - transformers-base
  - unordered-containers >= 0.1.3 && < 0.3
  - microlens-platform

library:
    source-dirs: src
    exposed-modules:
      - Yi.Buffer.Basic
      - Yi.Lexer.Alex
      - Yi.Lexer.Compilation
      - Yi.Regex
      - Yi.Region
      - Yi.Style
      - Yi.Style.Library
      - Yi.Syntax
      - Yi.Utils
    build-tools:
      - alex >= 3.0.3 && < 3.2.0 || >= 3.2.1
    include-dirs:
      - src/Yi/Lexer
    dependencies:
    - oo-prototypes

tests:
  tasty:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - yi-language